[package]
name = "crust_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.12"
png = "0.17"
winit = { version = "0.28", default_features = false, features = ["wayland"] }
bdf = "0.6.0"
serde = { version = "1.0.152", features = ["serde_derive"] }
toml = { version = "0.7.2" }
